# Generated by Django 3.1.2 on 2021-02-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='password',
            new_name='passwd',
        ),
    ]
