# Generated by Django 3.1.2 on 2021-02-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100)),
                ('modelNumber', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('weight', models.CharField(max_length=100)),
                ('totalnumofCells', models.CharField(max_length=100)),
                ('numberofseriesStrings', models.CharField(max_length=100)),
                ('seriesfuseRating', models.CharField(max_length=100)),
                ('frameType', models.CharField(max_length=100)),
                ('maxVoltage', models.CharField(max_length=100)),
                ('voc', models.CharField(max_length=100)),
                ('isc', models.CharField(max_length=100)),
                ('vmp', models.CharField(max_length=100)),
                ('imp', models.CharField(max_length=100)),
                ('pmp', models.CharField(max_length=100)),
                ('ff', models.CharField(max_length=100)),
            ],
        ),
    ]
